version: '3.8'

services:
  mdweb:
    build:
      context: .
      target: react

  nginx:
    build:
      context: .
      target: nginx
    image: 'sedsnepal_md_web:latest'
    container_name: sedsnepal_md_web
    ports:
      - "8080:80"