version: '3.8'

services:
  app:
    image: 'supernovabirth/sedsnepal_md_app:latest'
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    container_name: sedsnepal_md_app
    ports:
      - 8000:8000
    depends_on:
      - mdb
    environment:
      - DATASOURCE_URL=postgresql://sedsnepal_md:sedsnepal_md@mdb:5432/sedsnepal_md

  mdb:
    image: 'postgres:13.3-alpine'
    container_name: mdb
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=sedsnepal_md
      - POSTGRES_USER=sedsnepal_md
      - POSTGRES_PASSWORD=sedsnepal_md
    volumes:
      - sedsnepal_md_data:/var/lib/postgresql/data

volumes:
  sedsnepal_md_data:
    driver: local