import * as yup from 'yup';

export const userSchema = yup.object().shape({
    first_name: yup.string().required(),
    middle_name:yup.string(),
    last_name:yup.string().required(),
    email:yup.string().email().required(),
    number:yup.number(10).required(),
    personsid: yup.number().required(),
    city:yup.string().required(),
    // province:yup.string().required(),
    postal_code:yup.number().required(),
    // postalcode:yup.string().min(5).max(10).required(),
    education_level:yup.string().required(),
    college_name:yup.string(),
    college_address:yup.string(),
    major:yup.string(),
    year:yup.number(),
    college_website:yup.string(),
    school_name:yup.string(),
    school_address:yup.string(),
    // class:yup.number().required(),
    school_website: yup.string(),
    company_name:yup.string(),
    company_address:yup.string(),
    position:yup.string(),
    // linkedinId:yup.string().number(),
    // ques1:yup.string().required(),
    // ques2:yup.string().required(),
});

