name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./backend
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push FastAPI
      uses: docker/build-push-action@v3
      with:
        context: backend
        file: backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sedsnepal_md_app:latest
    - name: Build and push React
      uses: docker/build-push-action@v3
      with:
        context: frontend
        file: frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sedsnepal_md_web:latest
  
  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
          insecure_ignore_fingerprint: true
          source: |
            backend/docker-compose.yml
          target: /home/backend/
      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
          insecure_ignore_fingerprint: true          
          source: |
            frontend/docker-compose.yml
          target: /home/frontend/
  
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    
    steps:

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: |
            sudo docker-compose -f backend/docker-compose.yml down
            sudo docker-compose -f frontend/docker-compose.yml down
            sudo docker rmi supernovabirth/sedsnepal_md_app
            sudo docker rmi supernovabirth/sedsnepal_md_web
            sudo docker-compose -f backend/docker-compose.yml up
            sudo docker-compose -f frontend/docker-compose.yml up
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
        privateKey: ${{ secrets.DIGITAL_OCEAN}}
