name: Docker Run

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
      
jobs:
  
  upload:
    name: Upload
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          fingerprint: ${{ secrets.DIGITAL_OCEAN_1 }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
          insecure_ignore_fingerprint: false
          source: |
            backend/docker-compose.yml
          target: /home/backend/
      - name: Upload file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          fingerprint: ${{ secrets.DIGITAL_OCEAN_1 }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
          insecure_ignore_fingerprint: false          
          source: |
            frontend/docker-compose.yml
          target: /home/frontend/
  
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    
    steps:

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: |
            sudo docker-compose -f backend/docker-compose.yml down
            sudo docker-compose -f frontend/docker-compose.yml down
            sudo docker rmi supernovabirth/sedsnepal_md_app
            sudo docker rmi supernovabirth/sedsnepal_md_web
            sudo docker-compose -f backend/docker-compose.yml up
            sudo docker-compose -f frontend/docker-compose.yml up
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        passphrase: ${{ secrets.DIGITAL_OCEAN_PASSPHRASE }}
        privateKey: ${{ secrets.DIGITAL_OCEAN}}
